abort_key_prefix = 'arq:abort:'
default_queue_name = 'arq:queue'
job_key_prefix = 'arq:job:'
in_progress_key_prefix = 'arq:in-progress:'
partial_result_key_prefix = 'arq:result-partial:'
result_key_prefix = 'arq:result:'
retry_key_prefix = 'arq:retry:'
health_check_key_suffix = ':health-check'
